/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

import url from '../../../assets/ghosttown.mp4';

import * as THREE from 'three';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/tv.gltf');
  const [video, setVideo] = useState(() => {
    const vid = document.createElement('video');
    vid.src = url;
    vid.crossOrigin = 'Anonymous';
    vid.loop = true;
    vid.muted = true;
    vid.play();
    return vid;
  });

  return (
    <group
      ref={group}
      {...props}
      rotation={props.groupRotation}
      // rotation={[0, 0, 0]}
      dispose={null}
    >
      <mesh
        geometry={nodes.TV.geometry}
        material={materials.Plastic}
        position={props.mesh1Position}
      >
        <meshStandardMaterial color="white" />
      </mesh>
      <mesh position={props.mesh2Position} rotation={props.mesh2Rotation}>
        <planeGeometry args={[3.2, 1.9]} />
        <meshStandardMaterial emissive={'white'} side={THREE.DoubleSide}>
          <videoTexture attach="map" args={[video]} />
          <videoTexture attach="emissiveMap" args={[video]} />
        </meshStandardMaterial>
      </mesh>
    </group>
  );
}

useGLTF.preload('/tv.gltf');
